# Generated by Django 3.2.8 on 2021-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='adharno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='voterid',
            field=models.CharField(max_length=15),
        ),
    ]
