# Generated by Django 4.0 on 2022-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_auto_20211022_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('Issue', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
