# Generated by Django 4.0 on 2022-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_contact_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('adharno', models.CharField(max_length=255)),
                ('voterid', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=100)),
            ],
        ),
    ]
