# Generated by Django 4.0 on 2022-05-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_alter_verificationdetails_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdetails',
            name='age',
        ),
    ]
